name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install deps
        run: npm ci --no-fund --no-audit
      - name: Lint
        run: npm run lint --silent
      - name: Typecheck
        run: npx tsc -p tsconfig.app.json --noEmit
      - name: Build
        run: npm run build --silent
      - name: Audit (report only)
        run: |
          set -e
          npm audit --json > audit.json || true
          echo "Saved audit report to audit.json"
